// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorDataPublisher.cpp
 * This file contains the implementation of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#include "SensorDataPublisher.h"
#include "SensorDataPubSubTypes.h"

#include <iostream>
#include <iomanip>
#include <vector>
#include <string>

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/publisher/Publisher.hpp>
#include <fastdds/dds/publisher/qos/PublisherQos.hpp>
#include <fastdds/dds/publisher/DataWriter.hpp>
#include <fastdds/dds/publisher/qos/DataWriterQos.hpp>

#include <thread>
#include <chrono>
#include <random>    // 난수 생성을 위해 추가

using namespace eprosima::fastdds::dds;

SensorDataPublisher::SensorDataPublisher(int id)
    : participant_(nullptr)
    , publisher_(nullptr)
    , topic_(nullptr)
    , writer_(nullptr)
    , type_(new SensorDataPubSubType())
    , m_id(id)
{
    std::cout << "SensorDataPublisher initialized (id: " << id << ")" << std::endl;
}


SensorDataPublisher::~SensorDataPublisher()
{
    if (writer_ != nullptr)
    {
        publisher_->delete_datawriter(writer_);
    }
    if (publisher_ != nullptr)
    {
        participant_->delete_publisher(publisher_);
    }
    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
    }
    DomainParticipantFactory::get_instance()->delete_participant(participant_);
}


bool SensorDataPublisher::init()
{
    /* Initialize data_ here */

    //CREATE THE PARTICIPANT
    DomainParticipantQos pqos;
    pqos.name("Participant_pub");
    uint32_t domain_id = getenv("ROS_DOMAIN_ID") ? std::atoi(getenv("ROS_DOMAIN_ID")) : 204;
    participant_ = DomainParticipantFactory::get_instance()->create_participant(domain_id, pqos);
    if (participant_ == nullptr)
    {
        std::cerr << "Failed to create DomainParticipant" << std::endl;
        return false;
    }

    //REGISTER THE TYPE
    type_.register_type(participant_);

    //CREATE THE PUBLISHER
    publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
    if (publisher_ == nullptr)
    {
        std::cerr << "Failed to create Publisher" << std::endl;
        return false;
    }

    //CREATE THE TOPIC
    topic_ = participant_->create_topic(
        "rt/SensorDataTopic",
        type_.get_type_name(),
        TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        std::cerr << "Failed to create Topic" << std::endl;
        return false;
    }

    // CREATE THE WRITER
    DataWriterQos wqos = DATAWRITER_QOS_DEFAULT;
    wqos.reliability().kind = BEST_EFFORT_RELIABILITY_QOS;
    writer_ = publisher_->create_datawriter(topic_, wqos, &listener_);
    if (writer_ == nullptr)
    {
        std::cerr << "Failed to create DataWriter" << std::endl;
        return false;
    }

    std::cout << "SensorData DataWriter created." << std::endl;

    return true;
}

void SensorDataPublisher::publish(const SensorData& data)
{
    if (writer_ != nullptr)
    {
        writer_->write(const_cast<SensorData*>(&data));
    }
}

void SensorDataPublisher::PubListener::on_publication_matched(
        eprosima::fastdds::dds::DataWriter*,
        const eprosima::fastdds::dds::PublicationMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        std::cout << "DataWriter matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        std::cout << "DataWriter unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for PublicationMatchedStatus current count change" << std::endl;
    }
}

#include <atomic>

void SensorDataPublisher::run()
{
    std::cout << "SensorData DataWriter waiting for DataReaders." << std::endl;
    while (listener_.matched == 0)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(250));
    }
    std::cout << "DataWriter matched. Running..." << std::endl;
}

