// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorDataSubscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>

#include "SensorDataSubscriber.h"
#include "SensorDataPubSubTypes.h"
#include <iomanip>
#include <sstream>
#include <vector>
#include <iostream>
#include <cctype>
#include <atomic>

std::atomic<bool> g_enable_sensor_log(true);

using namespace eprosima::fastdds::dds;

SensorDataSubscriber::SensorDataSubscriber()
    : participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    , type_(new SensorDataPubSubType())
{
    listener_.parent = this;
}

SensorDataSubscriber::~SensorDataSubscriber()
{
    if (reader_ != nullptr)
    {
        subscriber_->delete_datareader(reader_);
    }
    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
    }
    if (subscriber_ != nullptr)
    {
        participant_->delete_subscriber(subscriber_);
    }
    DomainParticipantFactory::get_instance()->delete_participant(participant_);
}

bool SensorDataSubscriber::init()
{
    //CREATE THE PARTICIPANT
    DomainParticipantQos pqos;
    pqos.name("Participant_sub");
    uint32_t domain_id = getenv("ROS_DOMAIN_ID") ? std::atoi(getenv("ROS_DOMAIN_ID")) : 204;
    participant_ = DomainParticipantFactory::get_instance()->create_participant(domain_id, pqos);
    if (participant_ == nullptr)
    {
        return false;
    }

    //REGISTER THE TYPE
    type_.register_type(participant_);

    //CREATE THE SUBSCRIBER
    subscriber_ = participant_->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr);
    if (subscriber_ == nullptr)
    {
        return false;
    }

    //CREATE THE TOPIC
    topic_ = participant_->create_topic(
        "rt/SensorDataTopic",
        type_.get_type_name(),
        TOPIC_QOS_DEFAULT);
    if (topic_ == nullptr)
    {
        return false;
    }

    //CREATE THE READER
    DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
    rqos.reliability().kind = BEST_EFFORT_RELIABILITY_QOS;
    reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
    if (reader_ == nullptr)
    {
        return false;
    }

    return true;
}

SensorDataSubscriber::ControlState SensorDataSubscriber::getControlState()
{
    std::lock_guard<std::mutex> lock(control_mutex_);
    return latest_control_;
}

void SensorDataSubscriber::SubListener::on_subscription_matched(
        DataReader*,
        const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        if (g_enable_sensor_log.load()) {
            std::cout << "Subscriber matched." << std::endl;
        }
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        if (g_enable_sensor_log.load()) {
            std::cout << "Subscriber unmatched." << std::endl;
        }
    }
    else
    {
        if (g_enable_sensor_log.load()) {
            std::cout << info.current_count_change
                      << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
        }
    }
}

void SensorDataSubscriber::SubListener::print_hex_and_ascii(const uint8_t* data, size_t length)
{
    for (size_t i = 0; i < length; i += 16)
    {
        // Hex part
        std::stringstream ss_hex;
        for (size_t j = 0; j < 16; ++j)
        {
            if (i + j < length)
            {
                ss_hex << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(data[i + j]) << " ";
            }
            else
            {
                ss_hex << "   ";
            }
        }

        // ASCII part
        std::stringstream ss_ascii;
        for (size_t j = 0; j < 16; ++j)
        {
            if (i + j < length)
            {
                char c = data[i + j];
                ss_ascii << (std::isprint(c) ? c : '.');
            }
        }

        std::cout << ss_hex.str() << " | " << ss_ascii.str() << " |" << std::endl;
    }
}

void SensorDataSubscriber::SubListener::on_data_available(
        DataReader* reader)
{
    // Take data
    SensorData st;
    SampleInfo info;

    if (reader->take_next_sample(&st, &info) == ReturnCode_t::RETCODE_OK)
    {
        if (info.valid_data)
        {
            // Print formatted data
            ++samples;
            if (st.sensor_name() == "VEHICLE_CONTROL" && st.data().size() >= 5)
            {
                std::lock_guard<std::mutex> lock(parent->control_mutex_);
                parent->latest_control_.steering = st.data()[0];
                parent->latest_control_.accelerator = st.data()[1];
                parent->latest_control_.brake = st.data()[2];
                parent->latest_control_.blinker = (int)st.data()[3];
                parent->latest_control_.manual_mode = (bool)st.data()[4];
                
                if (st.data().size() >= 14) {
                    parent->latest_control_.roi_h_axis = st.data()[5];
                    parent->latest_control_.roi_g_axis = st.data()[6];
                    parent->latest_control_.lidar_btn = (st.data()[7] > 0.5);
                    parent->latest_control_.camera_btn = (st.data()[8] > 0.5);
                    parent->latest_control_.bev_btn = (st.data()[9] > 0.5);
                    parent->latest_control_.mode_btn = (st.data()[10] > 0.5);
                    parent->latest_control_.speed_up_btn = (st.data()[11] > 0.5);
                    parent->latest_control_.speed_down_btn = (st.data()[12] > 0.5);
                    parent->latest_control_.stop_btn = (st.data()[13] > 0.5);
                    
                    if (st.data().size() >= 18) {
                        parent->latest_control_.lidar_dist_down_btn = (st.data()[14] > 0.5); // Select
                        parent->latest_control_.lidar_dist_up_btn = (st.data()[15] > 0.5);   // Start
                        parent->latest_control_.l1_btn = (st.data()[16] > 0.5);             // L1 Raw
                        parent->latest_control_.r1_btn = (st.data()[17] > 0.5);             // R1 Raw
                    }
                }
                parent->latest_control_.samples++;
            }
            else if (st.sensor_name() == "IMU" && st.data().size() >= 3)
            {
                std::lock_guard<std::mutex> lock(parent->control_mutex_);
                parent->latest_control_.imu[0] = st.data()[0];
                parent->latest_control_.imu[1] = st.data()[1];
                parent->latest_control_.imu[2] = st.data()[2];
            }
            else if (st.sensor_name() == "ADC_SENSORS" && st.data().size() >= 5)
            {
                std::lock_guard<std::mutex> lock(parent->control_mutex_);
                parent->latest_control_.ir[0] = st.data()[0];
                parent->latest_control_.ir[1] = st.data()[1];
                parent->latest_control_.ir[2] = st.data()[2];
                parent->latest_control_.ultra = st.data()[3];
                parent->latest_control_.batt  = st.data()[4];
            }
            else if (st.sensor_name() == "GROUND_TRUTH" && st.data().size() >= 3)
            {
                std::lock_guard<std::mutex> lock(parent->control_mutex_);
                parent->latest_control_.gt_x = st.data()[0];
                parent->latest_control_.gt_y = st.data()[1];
                parent->latest_control_.gt_yaw = st.data()[2];
                parent->latest_control_.gt_updated = true;
            }
            else if (st.sensor_name() == "CAMERA_LANE")
            {
                std::lock_guard<std::mutex> lock(parent->control_mutex_);
                parent->latest_control_.latest_image_base64 = st.status();
            }

            // [신규] 터미널에 통합 실시간 데이터 출력 (\r 사용으로 한 줄 유지)
            if (g_enable_sensor_log)
            {
                if (st.sensor_name() == "VEHICLE_CONTROL" || st.sensor_name() == "IMU" || st.sensor_name() == "ADC_SENSORS")
                {
                    std::lock_guard<std::mutex> lock(parent->control_mutex_);
                    auto& c = parent->latest_control_;
                    std::cout << "\r[VEH] S:" << std::fixed << std::setprecision(1) << c.steering
                              << " M:" << (c.manual_mode ? "MAN" : "AUT")
                              << " | [IMU] R:" << std::setw(5) << (int)c.imu[0] << " P:" << std::setw(5) << (int)c.imu[1] << " Y:" << std::setw(5) << (int)c.imu[2]
                              << " | [ADC] IR:" << (int)c.ir[0] << "," << (int)c.ir[1] << "," << (int)c.ir[2]
                              << " US:" << std::setprecision(2) << c.ultra << "m B:" << std::setprecision(1) << c.batt << "V"
                              << "    " << std::flush;
                }
                else
                {
                     std::cout << "\n[DDS] Received: " << st.sensor_name() 
                               << " (Size: " << st.status().length() << ")" << std::endl;
                }
            }


/* 
            // Raw Binary Packet Dump 
            SensorDataPubSubType type;
            eprosima::fastrtps::rtps::SerializedPayload_t payload(type.m_typeSize);
            if (type.serialize(&st, &payload))
            {
                std::cout << "--- Raw Binary Packet (Length: " << payload.length << " bytes) ---" << std::endl;
                print_hex_and_ascii(payload.data, payload.length);
                std::cout << "-----------------------------------------------" << std::endl;
            }
*/
        }
    }
}

void SensorDataSubscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the DataReader. " << std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}
