// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file SensorDataPubSubMain.cpp
 * This file acts as a main entry point to the application.
 *
 * This file was generated by the tool fastcdrgen.
 */


#include "SensorDataPublisher.h"
#include "SensorDataSubscriber.h"
#include <iostream>
#include <string>
#include <cstring>

int main(
        int argc,
        char** argv)
{
    int type = 0;

    int sensor_id = 1;

    if (argc >= 2)
    {
        if (strcmp(argv[1], "publisher") == 0)
        {
            type = 1;
            if (argc == 3)
            {
                sensor_id = std::stoi(argv[2]);
            }
        }
        else if (strcmp(argv[1], "subscriber") == 0)
        {
            type = 2;
        }
    }

    if (type == 0)
    {
        std::cout << "Error: Incorrect arguments." << std::endl;
        std::cout << "Usage: " << std::endl << std::endl;
        std::cout << argv[0] << " publisher [id]|subscriber" << std::endl << std::endl;
        return 0;
    }

    std::cout << "Starting (type: " << type << ", sensor_id: " << sensor_id << ")" << std::endl;

    // Register the type being used

    switch (type)
    {
        case 1:
        {
            std::cout << "Creating publisher..." << std::endl;
            SensorDataPublisher mypub(sensor_id);
            std::cout << "Initializing publisher..." << std::endl;
            if (mypub.init())
            {
                std::cout << "Running publisher... (Interactive)" << std::endl;
                mypub.run();
            }
            else
            {
                std::cerr << "Publisher init failed!" << std::endl;
            }
            break;
        }
        case 2:
        {
            SensorDataSubscriber mysub;
            if (mysub.init())
            {
                mysub.run();
            }
            break;
        }
    }

    return 0;
}
